builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.isGitDirty={{ .IsGitDirty }}"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    rlcp: true
    files:
      - README.md
      - LICENSE
      - docs/*.md

brews:
  - tap:
      owner: gontainer
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage:  https://github.com/gontainer/gontainer
    description: DI container for GO
    license: MIT
    test: |
      system "#{bin}/gontainer -v"
    dependencies:
      - name: go
        type: optional
      - name: git
    install: |-
      bin.install "gontainer"
    commit_author:
      name: bkrukowski
      email: krukowski.bartlomiej@gmail.com

checksum:
  name_template: 'checksums.txt'
