{{- /*gotype: github.com/gontainer/gontainer/internal/pkg/template.data*/ -}}
// Code generated by https://github.com/gontainer/gontainer; DO NOT EDIT.

package {{.Output.Meta.Pkg}}

// gontainer {{ .BuildInfo }}

{{range $import := .ImportCollection.Imports -}}
import {{$import.Alias}} "{{$import.Path}}"
{{end}}
