name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
          BREW_TAG_PUSHER_NAME: ${{ github.event.pusher.name }}
          BREW_TAG_PUSHER_EMAIL: ${{ github.event.pusher.email }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

  bootstrapping:
    needs: goreleaser
    name: Bootstrapping PR
    runs-on: macos-latest
    steps:
      - run: echo "GONTAINER_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "Gontainer $GONTAINER_VERSION"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: brew install gontainer/homebrew-tap/gontainer
      - run: gontainer -v
      - run: git checkout -B bootstrapping/$GONTAINER_VERSION
      - run: make self-compile
      - run: "git config user.name 'github-actions[bot]'"
      - run: "git config user.email 'github-actions[bot]@users.noreply.github.com'"
      - run: 'git commit -m "feat(bootstrapping): gontainer $GONTAINER_VERSION" internal/gontainer/gontainer.go'
      - run: "git push --set-upstream origin bootstrapping/$GONTAINER_VERSION"
      - name: Create pull request
        run: 'gh pr create --base=main --body="[Generated by 🤖](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" --fill-first --no-maintainer-edit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}