name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

env:
  GOPROXY: direct

jobs:

  build:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20' ]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Test
      run: |
        make tests-unit
        make tests-functional

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
        flag-name: Go-${{ matrix.go }}
