name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21' ]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: false

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Get dependencies
      run: go mod vendor

    - name: Build
      run: make build

    - name: Test
      run: |
        make tests-unit
        make tests-functional

    - name: Test coverage
      run: make code-coverage

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
        flag-name: Go-${{ matrix.go }}
